### ISSUE TITLE
Composer Code Lab: Issue with creating URL

### ISSUE THREAD

**Issue by jaketf** [GoogleCloudPlatform/professional-services#462]
I'm running the lab now, and I got stuck trying to construct the Endpoint URL.

Here are the instructions and command (I'm assuming you don't actually replace anything since environment variables were created). 
Construct your endpoint by running the following in Cloud Shell, replacing and updating the with the information you saved:
```
python dag_trigger.py \
--url="${AIRFLOW_URI}/api/experimental/dags/average-speed/dag_runs" \
--iapClientId=$CLIENT_ID \
--raw_path=gs://$PROJECT/cloud-composer-lab/raw-$EXPORT_TS/
```
And this is the error:
```
(venv) student_00_f3a493604a22@cloudshell:~/professional-services/examples/cloud-composer-examples/composer_http_post_example (qwiklabs-gcp-00-ab87f60eadec)$ python dag_trigger.py \
> --url="${AIRFLOW_URI}/api/experimental/dags/average-speed/dag_runs" \
> --iapClientId=$CLIENT_ID \
> --raw_path=gs://$PROJECT/cloud-composer-lab/raw-$EXPORT_TS/
Traceback (most recent call last):
  File "/home/student_00_f3a493604a22/professional-services/examples/cloud-composer-examples/composer_http_post_example/venv/lib/python3.7/site-packages/google/auth/compute_engine/credentials.py", line 289, in _call_metadata_identity_endpoint
    self._target_audience
  File "/home/student_00_f3a493604a22/professional-services/examples/cloud-composer-examples/composer_http_post_example/venv/lib/python3.7/site-packages/google/auth/compute_engine/_metadata.py", line 172, in get
    response,
google.auth.exceptions.TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=350744924973-km59f4t2vvj8ii3cluaq26tflodev8bn.apps.googleusercontent.com&format=full from the Google Compute Enginemetadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7f19cbd32cf8>)
```
The above exception was the direct cause of the following exception:
```
Traceback (most recent call last):
  File "dag_trigger.py", line 100, in <module>
    main()
  File "dag_trigger.py", line 96, in main
    data=json.dumps(payload))
```

**Comment by jaketf** [comment]
Through my initial investigation, I am not able to reproduce the error you report in your latest email. For me the dag_trigger.py script runs successfully. However, I am able to reproduce the original issue that dataproc job is not starting. It appears the dag run is immediately being marked success rather than actually kicking off tasks.I'm able to patch this by changing the way we set start_date and schedule interval.This may have changed in more recent versions of airflow since the lab was written and now composer defaults to a newer airflow version.
This unfortunately was not the end of the road. I now observe that the dataproc cluster creation fails.It complains about the dataproc bucket not existing (typically the dataproc service is supposed to create this bucket I'm not sure what's going on here might be an issue with permissions in the org i was testing in).

We can work around this by adding two steps to the lab:
1. In the Create the Cloud Storage Bucket section 
```bash
export DATAPROC_BUCKET=$PROJECT-dataproc-staging
gsutil mb -c regional -l us-central1 gs://$DATAPROC_BUCKET
```

1.  In the section "Once the environment is created, set Airflow Variables in the Composer Environment you just created:
```bash
gcloud composer environments run demo-ephemeral-dataproc \
--location=us-central1 variables -- \
--set dataproc_bucket $DATAPROC_BUCKET
```
I have prepared #463  to make the code changes and updated my [blog post](https://medium.com/google-cloud/using-airflow-experimental-rest-api-on-google-cloud-platform-cloud-composer-and-iap-9bd0260f095a) on this same topic (albeit a bit prematurely).
