### ISSUE TITLE
Binance API calls  in java .. works fine from eclipse!  but GCP ALWAYS gives a server 500.. here is the trace/ full logs

### ISSUE THREAD

**Issue by johnda98** [GoogleCloudPlatform/professional-services#511]
The code works fine in Eclipse IDE from console... but server 500 in GCP ! pls help thanks

and yes the binance java api .jar is on my eclipse GCP build path sucked in.. so it should bundle that up when deploying to GCP.. its a standard App enigne .. is that the prob ?  we need flexible ?

https://console.cloud.google.com/logs/viewer?project=assetsalecrobv41-282617&resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2F20200710t120500&minLogLevel=0&expandAll=false&timestamp=2020-07-10T17%3A14%3A26.554000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2020-07-10T16%3A14%3A26.806Z&dateRangeEnd=2020-07-10T17%3A14%3A26.806Z&interval=PT1H&logName=projects%2Fassetsalecrobv41-282617%2Flogs%2Fappengine.googleapis.com%252Frequest_log&scrollTimestamp=2020-07-10T17%3A14%3A16.804597000Z&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.project_id%3D%22assetsalecrobv41-282617%22%0Aresource.labels.version_id%3D%2220200710t120500%22%0Aresource.labels.zone%3D%22us12%22%0Aresource.labels.module_id%3D%22default%22%0Atimestamp%3D%222020-07-10T17%3A14%3A16.804597000Z%22%0AinsertId%3D%225f08a1e8000ea45482d9c68f%22

here is the code.. i think i handle ALL the exceptions in the servlet class call

package asalegroup;

import com.binance.api.client.BinanceApiClientFactory;
import com.binance.api.client.BinanceApiRestClient;
import com.binance.api.client.domain.market.TickerStatistics;
import com.binance.api.client.exception.BinanceApiException;

public class Getcryptopair {
	
public static String getpair(String pair) throws BinanceApiException {
		
       String pairprice;
		
	
	   BinanceApiClientFactory factory = BinanceApiClientFactory.newInstance();
	   BinanceApiRestClient client = factory.newRestClient();
	   

	    // Test connectivity
	    client.ping();

	    //long serverTime = client.getServerTime();
	    //out.println("<p> Time of ticker from Binance - its Servertime : " + serverTime + "</p>");
  	
	    
		//TickerStatistics tickerStatistics = client.get24HrPriceStatistics("NEOETH");
		//out.println("<p> NEO ETH : " + tickerStatistics.getLastPrice() + "</p>");
  	
		
  	
		//String price = tickerStatistics.getLastPrice().toString();
		//out.println("<p> as string .. " + price + "</p>");
		
		TickerStatistics tickerStatistics = client.get24HrPriceStatistics(pair);
		//out.println("<p> HBAR USDT : " + tickerStatistics2.getLastPrice() + "</p>");
	     pairprice = tickerStatistics.getLastPrice();
		
		return pairprice;
		
		}
	   
	   

}

the servlet call...
package asalegroup;

import java.io.IOException;
import java.io.PrintWriter;

import java.util.logging.Logger;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class GetBinancepairs
 */
@WebServlet("/getusdhbar_rate/*")
public class GetBinancepairs extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public GetBinancepairs() {
        super();
        // TODO Auto-generated constructor stub
    }

    
	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		//response.getWriter().append("Served at: ").append(request.getContextPath());
	
		response.setContentType("text/html; charset=UTF-8");
	    PrintWriter out = response.getWriter();
	    
	   
	    out.println("<!DOCTYPE html>");
	    out.println("<html><head>");
	    
	    out.println("<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>");
	    out.println("<title>CRob Smart Contract interaction. Hedera Hashgraph Testnet</title></head>");
	   
	    out.println("<body bgcolor=\"powderblue\"><font size=\"-8\">");
	    out.println("<h2><font face=\"arial\" >Hedera Hashgraph & Smart Contract 'Direct Asset' Example.</h2>"); 
	    
	    out.println("<h1>Binance USD HBAR pricing ...</h1>");
	    
	    out.println("<fieldset>");
        out.println("<legend></legend>");
        
        out.println("<p> </p> ");
        out.println("<p> Current pricing at this time of call to market is : " + Getcryptopair.getpair("HBARUSDT") + "</p>");
	    	

And the binance java api JAR is on my GCP project build path

but it seems tobe indicating it cand find the Class in the jar... stumped

"com.google.apphosting.runtime.jetty9.JettyLogger warn: Error for /getusdhbar_rate (JettyLogger.java:29)
java.lang.NoClassDefFoundError: com/binance/api/client/BinanceApiClientFactory"

**Comment by briandealwis** [comment]
@johnda98 it would help to include the full log output.  A `NoClassDefFoundError` can sometimes indicate a class-loading failure occurred earlier.

Cloud Tools for Eclipse (CTE) assembles an _exploded war_ when deploying to App Engine, found in `<workspace>/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/NNNN` where `NNNN` is the timestamp of the deploy.  CTE only retains the last two deploys.  Your libraries will be placed in `WEB-INF/lib`.  You should verify that they match your project's classpath.

**Comment by johnda98** [comment]
Thanks Brian.. I'll grab you that log

**Comment by johnda98** [comment]
https://console.cloud.google.com/logs/viewer?project=assetsalecrobv6&resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2F20200727t095154&minLogLevel=0&expandAll=false&timestamp=2020-07-27T14%3A56%3A40.931000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2020-07-27T13%3A56%3A41.190Z&dateRangeEnd=2020-07-27T14%3A56%3A41.190Z&interval=PT1H&logName=projects%2Fassetsalecrobv6%2Flogs%2Fappengine.googleapis.com%252Frequest_log&scrollTimestamp=2020-07-27T14%3A56%3A16.738607000Z&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.project_id%3D%22assetsalecrobv6%22%0Aresource.labels.zone%3D%22us14%22%0Aresource.labels.version_id%3D%2220200727t095154%22%0Atimestamp%3D%222020-07-27T14%3A56%3A16.738607000Z%22%0AinsertId%3D%225f1eeb190003d990bc911144%22

**Comment by johnda98** [comment]
yes its saying it can't find the Class.. but it runs fine form the console and the binance jar is in the project directory when I deploy to GCP as routine..   for some reason I had to download the binance jar.. maven source no good.. is that the issue.. cannot upload depedency jars to GCP standard app engine ?

2020-07-27 09:56:25.199 CDT
com.google.apphosting.runtime.jetty9.JettyLogger warn: Error for /getusdhbar_rate (JettyLogger.java:29)
java.lang.NoClassDefFoundError: com/binance/api/client/BinanceApiClientFactory
	at asalegroup.Getcryptopair.getpair(Getcryptopair.java:15)
	at asalegroup.GetBinancepairs.doGet(GetBinancepairs.java:58)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:762)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:725)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:695)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:887)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.binance.api.client.BinanceApiClientFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at com.google.apphosting.runtime.ApplicationClassLoader.findClass(ApplicationClassLoader.java:135)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more

**Comment by johnda98** [comment]
https://github.com/binance-exchange/binance-java-api/issues/171
2018 issue w binance depedency

**Comment by johnda98** [comment]
I used this API it worked on GCP / AWS just fine

  <dependency>
  <groupId>com.webcerebrium</groupId>
  <artifactId>binance-api</artifactId>
  <version>1.0.9</version>
</dependency>

**Comment by johnda98** [comment]
<dependency>
  <groupId>com.webcerebrium</groupId>
  <artifactId>binance-api</artifactId>
  <version>1.0.9</version>
</dependency>
