### ISSUE TITLE
gsuite-exporter only compatible with google-api-python-client < v1.18

### ISSUE THREAD

**Issue by Mrandyrew95** [GoogleCloudPlatform/professional-services#555]
The function `google.auth._default._load_credentials_from_file` is now a public method `google.auth._default.load_credentials_from_file`.

Attempting to authenticate thus causes error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew_ford2/.local/lib/python3.7/site-packages/gsuite_exporter/cli.py", line 23, in <module>
    from gsuite_exporter.collectors.reports import AdminReportsAPIFetcher
  File "/home/andrew_ford2/.local/lib/python3.7/site-packages/gsuite_exporter/collectors/reports.py", line 17, in <module>
    from gsuite_exporter import auth
  File "/home/andrew_ford2/.local/lib/python3.7/site-packages/gsuite_exporter/auth.py", line 19, in <module>
    from google.auth._default import _load_credentials_from_file
ImportError: cannot import name '_load_credentials_from_file' from 'google.auth._default' (/usr/local/lib/python3.7/dist-packages/google/auth/_default.py)
```

**Comment by ocervell** [comment]
Thanks for the report, sorry I've just seen it. Committing a fix very soon.

**Comment by agold-rh** [comment]
Closed as fixed.
