### ISSUE TITLE
[slo-generator] Prometheus Backend Query Issue

### ISSUE THREAD

**Issue by svenmueller** [GoogleCloudPlatform/professional-services#558]
```
---
service_name:      product
feature_name:      search
slo_name:          freshness
slo_description:   99% of messages in queue xyz are fresh
slo_target:        0.99
backend:
  class:           Prometheus
  method:          query_sli
  url:             https://my-prometheus.com
  headers:
    Content-Type:  application/json
    Authorization: Basic <username:password base64-encoded>
  measurement:
    expression:    >
      count_over_time((metric < 900)[window:1m])
      /
      count_over_time(metric[window])
exporters:
- class:           Stackdriver
  project_id:      ${stackdriver_host_project_id}
```

```
Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 402, in run_background_function _function_handler.invoke_user_function(event_object) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 222, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v1.py", line 219, in call_user_function event_context.Context(**request_or_event.context)) File "/user_code/main.py", line 46, in main do_export=True) File "/env/local/lib/python3.7/site-packages/slo_generator/compute.py", line 56, in compute delete=delete) File "/env/local/lib/python3.7/site-packages/slo_generator/report.py", line 84, in __init__ result = self.run_backend(config, client=client, delete=delete) File "/env/local/lib/python3.7/site-packages/slo_generator/report.py", line 175, in run_backend result = method(self.timestamp, self.window, config) File "/env/local/lib/python3.7/site-packages/slo_generator/backends/prometheus.py", line 61, in query_sli sli_value = float(data['data']['result'][0]['value'][1]) KeyError: 'data'
```

We verified that the base64 encoded username:password value is correct. Maybe the headers are missing in the request and therefore the server returns an unexpected payload?

CURL Example works and returns expected JSON payload:
```
curl -H "Authorization: Basic ..." https://my-prometheus.com/api/v1/query\?query\=count_over_time...

{"status":"success","data":{"resultType":"vector","result":[{"metric":{...},"value":[1600878831.127,"10080"]}]}}
```

Any ideas?

Thx,
Sven

**Comment by svenmueller** [comment]
The `PrometheusBackend` seems to function correctly:

```
from slo_generator.backends.prometheus import PrometheusBackend

backend = PrometheusBackend(url="https://thanos-query.europe-west1.gcp.escemo.com/", headers = {'Content-Type': 'application/json','Authorization': 'Basic ...'})

response = backend.client.query(metric='count_over_time((aws_sqs_approximate_age_of_oldest_message_maximum{queue_name="my-queue"} < 900)[7d:1m]) / count_over_time(aws_sqs_approximate_age_of_oldest_message_maximum{queue_name="my-queue"}[7d])')

print(response)
```

Response
```
{"status":"success","data":{"resultType":"vector","result":[{"metric":{...,"value":[1600961408.427,"1.0008942766295708"]}]}}
````

**Comment by svenmueller** [comment]
Ok, i think i narrowed down the issue:

We use the Prometheus backend method `query_sli` and pass the full PromQL query which contains multiple placeholders for the time window (`[window]`). Only one occurrence of the place holder gets replaced by the code in the class `PrometheusBackend` which results in an invalid PromQL query and therefore an unexpected payload for `slo-generator`.

This line should be changed to replace all occurrences of `[window]`:
```
expression = expr.replace("[window]", f"[{window}s]")
```

(https://github.com/GoogleCloudPlatform/professional-services/blob/master/tools/slo-generator/slo_generator/backends/prometheus.py#L56)

In general it might be a good idea to have a better error message in case a backend returns an unexpected payload (e.g. due to a wrong query).

**Comment by ocervell** [comment]
Hi Sven,
`replace` replaces any occurence in the string, so this is not the culprit.
I've ran your example and I'm getting a parsing error from the Prometheus client, here are the debug logs (you can enable them by setting `export DEBUG=1` before running locally:
```
llib3.connectionpool - DEBUG - http://35.233.27.156:9090 "GET /api/v1/query?query=count_over_time%28%28aws_sqs_approximate_age_of_oldest_message_ma
ximum%7Bqueue_name%3D%22my-queue%22%7D+%3C+900%29%5B7d%3A1m%5D%29+%2F+count_over_time%28aws_sqs_approximate_age_of_oldest_message_maximum%7Bqueue_nam
e%3D%22my-queue%22%7D%5B7d%5D%29%0A&time=1600965444.930466 HTTP/1.1" 400 125
slo_generator.backends.prometheus - DEBUG - {'error': 'parse error at char 97: unexpected "[" in function call, expected '
          '")"',
 'errorType': 'bad_data',
 'status': 'error'}
slo_generator.backends.prometheus - DEBUG - Expression: count_over_time((aws_sqs_approximate_age_of_oldest_message_maximum{queue_name="my-queue"} < 9
00)[7d:1m]) / count_over_time(aws_sqs_approximate_age_of_oldest_message_maximum{queue_name="my-queue"}[7d])
 | Result: {'error': 'parse error at char 97: unexpected "[" in function call, expected '
          '")"',
 'errorType': 'bad_data',
 'status': 'error'}
```

**Comment by ocervell** [comment]
Also, it seems you are not using the version with the Prom fix too: `pip uninstall slo-generator && pip install slo-generator == 1.1.1a0"

**Comment by ocervell** [comment]
Can you validate the query syntax in the Prometheus UI ? I'm getting an error there too.

**Comment by ocervell** [comment]
Are you using a recording rule currently for this ? 
Might be related to https://github.com/prometheus/prometheus/issues/1227

**Comment by svenmueller** [comment]
> Are you using a recording rule currently for this ?
> Might be related to prometheus/prometheus#1227

No, that's a metric exported from AWS cloudwatch-exporter (not created by a rexording rule).


Here is what i noticed. The following PromQL query doesn't work when running `slo-generator` locally:

```
backend:
  ...
  measurement:
    expression:    >
      count_over_time((aws_sqs_approximate_age_of_oldest_message_maximum{queue_name="my-queue"} < 900)[window:1m])
      /
      count_over_time(aws_sqs_approximate_age_of_oldest_message_maximum{queue_name="my-queue"}[window])
```

output
```
DEBUG: 2
Traceback (most recent call last):
  File "/usr/local/bin/slo-generator", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/slo_generator/cli.py", line 32, in main
    cli(args)
  File "/usr/local/lib/python3.8/site-packages/slo_generator/cli.py", line 65, in cli
    reports = compute(slo_config,
  File "/usr/local/lib/python3.8/site-packages/slo_generator/compute.py", line 52, in compute
    report = SLOReport(config=slo_config,
  File "/usr/local/lib/python3.8/site-packages/slo_generator/report.py", line 84, in __init__
    result = self.run_backend(config, client=client, delete=delete)
  File "/usr/local/lib/python3.8/site-packages/slo_generator/report.py", line 175, in run_backend
    result = method(self.timestamp, self.window, config)
  File "/usr/local/lib/python3.8/site-packages/slo_generator/backends/prometheus.py", line 61, in query_sli
    sli_value = float(data['data']['result'][0]['value'][1])
KeyError: 'data'
```

The following PromQL query does work when running `slo-generator` locally (i manually replaced "[window:1m]" with "[7d:1m]" for testing purpose):

```
backend:
  ...
  measurement:
    expression:    >
      count_over_time((aws_sqs_approximate_age_of_oldest_message_maximum{queue_name="my-queue"} < 900)[7d:1m])
      /
      count_over_time(aws_sqs_approximate_age_of_oldest_message_maximum{queue_name="my-queue}[window])
```

output
```
slo_generator.compute - INFO - product/search/freshness | 1 hour   | SLI: 20985.4167 % | SLO: 99.0 % | Gap: +20890.42% | BR: -4177.1 / 9 | Alert: False | Timestamp: 1600972698
slo_generator.compute - INFO - product/search/freshness | 12 hours | SLI: 1422.7401 % | SLO: 99.0 % | Gap: +1327.74% | BR: -264.5 / 3 | Alert: False | Timestamp: 1600972698
slo_generator.compute - INFO - product/search/freshness | 7 days   | SLI: 100.0894 % | SLO: 99.0 % | Gap: +5.09 % | BR: -0.0 / 1 | Alert: False | Timestamp: 1600972698
slo_generator.compute - INFO - product/search/freshness | 28 days  | SLI: 73.2316 % | SLO: 99.0 % | Gap: -21.77% | BR: 5.4 / 1 | Alert: True | Timestamp: 1600972698
```

**Comment by svenmueller** [comment]
Problem: The string "[window]" doesn't match "[window:1m]" and therefore the range will not be replaced which results in an invalid query.

(see https://github.com/GoogleCloudPlatform/professional-services/blob/master/tools/slo-generator/slo_generator/backends/prometheus.py#L56)

**Comment by ocervell** [comment]
Thanks for the details: the error for matching `[window]` or `[window:1m]` is already fixed by https://github.com/GoogleCloudPlatform/professional-services/pull/554 which is included in version `1.1.1a0`. I've just tested your SLO with Prometheus 2.21.0 and the query is working okay.

**Comment by ocervell** [comment]
It's because you're not setting the `slo_generator_version` in your SLO module. I've added a comment in your PR.

**Comment by svenmueller** [comment]
I can confirm it works when setting the slo-generator version to `1.1.1a0`. Thx for your support @ocervell 🏅
