### ISSUE TITLE
permission-discrepancy-finder not parsing input as it promises to

### ISSUE THREAD

**Issue by ChastinaLi** [GoogleCloudPlatform/professional-services#591]
README says project_ids_location requires location of json file, but the code expects a Json blob:

```
  `--project_ids_location:` [OPTIONAL] Location of json file path with the
    following schema containing the project ids.
```

```
$ python permission_discrepancy_finder.py \
--organization="organizations/balabah" \         
--resource="*-compute@developer.gserviceaccount.com*" \
--project_permissions="dataflow.jobs.create" \                            
--resource_permission="iam.serviceAccounts.actAs" \                        
--project_ids_location="~/professional-services/tools/permission-discrepancy-finder/projects.json" \
--service_account_file_path="fsdfsdfsdf.json" \
--to_json="~/professional-services/tools/permission-discrepancy-finder/output.json"

Traceback (most recent call last):
  File "permission_discrepancy_finder.py", line 402, in <module>
    main()
  File "permission_discrepancy_finder.py", line 383, in main
    project_ids = json.load(args.project_ids_location)["project_ids"]
  File "/opt/twitter_mde/package/eepython37/current/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
```

**Comment by agold-rh** [comment]
Closed due to inactivity.
