### ISSUE TITLE
Stacktrace with gcp-org-hierarchy-viewer (gcpohv)

### ISSUE THREAD

**Issue by lhriley** [GoogleCloudPlatform/professional-services#621]
Hello,

I was looking for a way to get a quick view of my folders and projects hierarchy and found this: https://github.com/GoogleCloudPlatform/professional-services/tree/main/tools/gcp-org-hierarchy-viewer

Unfortunately, this seems to be in a broken state / does not work with the instructions provided by the README.md. I suspect that since the code provided here is ~16 months old, it is no longer compatible with the current API client version.

When I try to simply run the command against my organization ID, I get the following stacktrace:

```
$ gcpohv -o <ID>
Traceback (most recent call last):
  File "/home/user/.local/bin/gcpohv", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/bin/gcpohv_cli.py", line 269, in main
    cli = Cli(args.key_file, args.organization, args.folder, args.use_id)
  File "/home/user/.local/bin/gcpohv_cli.py", line 101, in __init__
    self._crm_v1, self._crm_v2 = setup_clients(credentials_file)
  File "/home/user/.local/bin/gcpohv_cli.py", line 62, in setup_clients
    crm_v1 = discovery.build('cloudresourcemanager', 'v1', credentials=creds)
  File "/home/user/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 273, in build
    content = _retrieve_discovery_doc(
  File "/home/user/.local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 387, in _retrieve_discovery_doc
    raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: cloudresourcemanager  version: v1
```

I don't have the bandwidth to do any further investigation into, or to fix, this issue at the moment. However, my suspicion -- without digging deeper -- is that the `cloudresourcemanager v1` API is deprecated, and that the related code should be removed or wrapped in `try` statements to catch the error and move on without failing. For example here: https://github.com/GoogleCloudPlatform/professional-services/blob/bfc956a2ee8e0b6a0196bf60abfd631198a104d0/tools/gcp-org-hierarchy-viewer/gcpohv_cli.py#L62

System information:
```
$ uname -a
Linux 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue.net
Linux Mint 20.1 Ulyssa

$ python --version
Python 3.8.5

$ pip list | grep google
google-api-core          1.26.0
google-api-python-client 2.0.0
google-auth              1.27.0
google-auth-httplib2     0.0.4
googleapis-common-protos 1.53.0
```

**Comment by angstwad** [comment]
@lhriley There might be something more complex going on, but I'll have to dig in a bit more... I'm on a Mac in a fresh and empty virtual environment, using `pyenv`, and it's installing and working for me.

```
✔ ~
09:54 $ pyenv versions
  system
* 3.8.7 (set by /Users/durivage/.pyenv/version)

✔ ~
09:54 $ mktmpenv
created virtual environment CPython3.8.7.final.0-64 in 435ms
  creator CPython3Posix(dest=/Users/durivage/Projects/Python/virtualenvs/tmp-67d48790ccf8cc3, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/durivage/Library/Application Support/virtualenv)
    added seed packages: pip==21.0.1, setuptools==53.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
virtualenvwrapper.user_scripts creating /Users/durivage/Projects/Python/virtualenvs/tmp-67d48790ccf8cc3/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/durivage/Projects/Python/virtualenvs/tmp-67d48790ccf8cc3/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/durivage/Projects/Python/virtualenvs/tmp-67d48790ccf8cc3/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/durivage/Projects/Python/virtualenvs/tmp-67d48790ccf8cc3/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/durivage/Projects/Python/virtualenvs/tmp-67d48790ccf8cc3/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.

(tmp-67d48790ccf8cc3) ✔ ~/Projects/Python/virtualenvs/tmp-67d48790ccf8cc3
09:54 $ pip3 install 'git+https://github.com/GoogleCloudPlatform/professional-services.git#egg=gcp-org-hierarchy-viewer&subdirectory=tools/gcp-org-hierarchy-viewer'
Collecting gcp-org-hierarchy-viewer
  Cloning https://github.com/GoogleCloudPlatform/professional-services.git to /private/var/folders/2z/482cy6696qlcdkghq4r8mbrh00kpks/T/pip-install-oabxclu_/gcp-org-hierarchy-viewer_da0628c4bc664ab281ccdb67887110f8
  Running command git clone -q https://github.com/GoogleCloudPlatform/professional-services.git /private/var/folders/2z/482cy6696qlcdkghq4r8mbrh00kpks/T/pip-install-oabxclu_/gcp-org-hierarchy-viewer_da0628c4bc664ab281ccdb67887110f8
Collecting google-api-python-client>=1.7.8
  Downloading google_api_python_client-2.1.0-py2.py3-none-any.whl (6.6 MB)
     |████████████████████████████████| 6.6 MB 7.0 MB/s
Collecting asciitree==0.3.3
... (truncated intentionally)
Successfully built gcp-org-hierarchy-viewer
Installing collected packages: six, pyasn1, urllib3, rsa, pyparsing, pyasn1-modules, protobuf, idna, chardet, certifi, cachetools, requests, pytz, packaging, httplib2, googleapis-common-protos, google-auth, uritemplate, google-auth-httplib2, google-api-core, google-api-python-client, asciitree, gcp-org-hierarchy-viewer
Successfully installed asciitree-0.3.3 cachetools-4.2.1 certifi-2020.12.5 chardet-4.0.0 gcp-org-hierarchy-viewer-1.0 google-api-core-1.26.3 google-api-python-client-2.1.0 google-auth-1.28.0 google-auth-httplib2-0.1.0 googleapis-common-protos-1.53.0 httplib2-0.19.1 idna-2.10 packaging-20.9 protobuf-3.15.7 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyparsing-2.4.7 pytz-2021.1 requests-2.25.1 rsa-4.7.2 six-1.15.0 uritemplate-3.0.1 urllib3-1.26.4

(tmp-67d48790ccf8cc3) ✔ ~/Projects/Python/virtualenvs/tmp-67d48790ccf8cc3
09:54 $ which gcpohv
/Users/durivage/Projects/Python/virtualenvs/tmp-67d48790ccf8cc3/bin/gcpohv
(tmp-67d48790ccf8cc3) ✔ ~/Projects/Python/virtualenvs/tmp-67d48790ccf8cc3

09:54 $ gcpohv -o hamsandwich.es
🏢 hamsandwich.es (448586408888)
... (truncated intentionally)
```

**Comment by lhriley** [comment]
@angstwad hmm. That is very strange. I just tested again with a fresh `virtualenv` and using your log as a guide. The result was the exact same issue.

Just to be sure this wasn't an API configuration issue, I verified that the `cloudresourcemanager.googleapis.com` API is enabled and refreshed my `gcloud` credentials. Are there any other APIs that are expected to be enabled, but are undocumented?

**Comment by lhriley** [comment]
Thanks @angstwad

**Comment by rosmo** [comment]
@lhriley If you go a `curl -i https://cloudresourcemanager.googleapis.com/$discovery/rest?version=v1`, what do you get? Do you have a proxy maybe?

**Comment by rosmo** [comment]
My credentials were there, but I wasn't running in GCP actually. So the information about zone, instance name, etc wasn't available (I mean, I suppose it would be better not to crash...).

**Comment by sumeetoc** [comment]
FYI, I was able to use it in debian 10 with following steps:

1. Github pip3 install command
2. Authentication using gcloud auth application-default login
3. Using either --use-id or just -o flags, both worked
