### ISSUE TITLE
tools/bq-visualizer failed to build 

### ISSUE THREAD

**Issue by nikunjbhartia** [GoogleCloudPlatform/professional-services#714]
Command : 
` gcloud builds submit --config cloudbuild.yaml --substitutions="_BQVISUALISER_BUCKET=<test-bucket-name>`

```
Step #0:   g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/builder/home/.node-gyp/14.10.0/include/node -I/builder/home/.node-gyp/14.10.0/src -I/builder/home/.node-gyp/14.10.0/deps/openssl/config -I/builder/home/.node-gyp/14.10.0/deps/openssl/openssl/include -I/builder/home/.node-gyp/14.10.0/deps/uv/include -I/builder/home/.node-gyp/14.10.0/deps/zlib -I/builder/home/.node-gyp/14.10.0/deps/v8/include -I../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
Step #0: ../src/create_string.cpp: In function 'char* create_string(Nan::MaybeLocal<v8::Value>)':
Step #0: ../src/create_string.cpp:17:37: error: no matching function for call to 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)'
Step #0:    v8::String::Utf8Value string(value);
Step #0:                                      ^
Step #0: In file included from /builder/home/.node-gyp/14.10.0/include/node/node.h:67:0,
Step #0:                  from ../../nan/nan.h:53,
Step #0:                  from ../src/create_string.cpp:1:
Step #0: /builder/home/.node-gyp/14.10.0/include/node/v8.h:3287:5: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
Step #0:      Utf8Value(Isolate* isolate, Local<v8::Value> obj);
Step #0:      ^~~~~~~~~
Step #0: /builder/home/.node-gyp/14.10.0/include/node/v8.h:3287:5: note:   candidate expects 2 arguments, 1 provided
Step #0: binding.target.mk:131: recipe for target 'Release/obj.target/binding/src/create_string.o' failed
Step #0: make: Leaving directory '/workspace/node_modules/node-sass/build'
Step #0: make: *** [Release/obj.target/binding/src/create_string.o] Error 1
Step #0: gyp ERR! build error 
Step #0: gyp ERR! stack Error: `make` failed with exit code: 2
Step #0: gyp ERR! stack     at ChildProcess.onExit (/workspace/node_modules/node-gyp/lib/build.js:262:23)
Step #0: gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
Step #0: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
Step #0: gyp ERR! System Linux 5.4.0-1052-gcp
Step #0: gyp ERR! command "/usr/local/bin/node" "/workspace/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
Step #0: gyp ERR! cwd /workspace/node_modules/node-sass
Step #0: gyp ERR! node -v v14.10.0
Step #0: gyp ERR! node-gyp -v v3.8.0
Step #0: gyp ERR! not ok 
Step #0: Build failed with error code: 1
Step #0: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
Step #0: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
Step #0: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 (node_modules/node-sass):
Step #0: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 postinstall: `node scripts/build.js`
Step #0: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
Step #0: 
Step #0: added 1263 packages from 1258 contributors and audited 1390 packages in 202.003s
Step #0: found 259 vulnerabilities (1 low, 74 moderate, 146 high, 38 critical)
Step #0:   run `npm audit fix` to fix them, or `npm audit` for details
Finished Step #0
Starting Step #1
Step #1: Already have image (with digest): gcr.io/cloud-builders/npm
Step #1: 
Step #1: > bq-viz@0.1.1 build /workspace
Step #1: > ng build "--prod"
Step #1:
Step #1: Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Step #1: 
Step #1: Date: 2021-11-09T05:16:06.383Z
Step #1: Hash: 1a29f1733d1aa8d43184
Step #1: Time: 230037ms
Step #1: chunk {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 1.41 kB [entry] [rendered]
Step #1: chunk {1} main.4676ba3fae7420b1a81f.js (main) 2.02 MB [initial] [rendered]
Step #1: chunk {2} polyfills.59d692cfbbd23ff7e836.js (polyfills) 61.7 kB [initial] [rendered]
Step #1: chunk {3} styles.baa94c1066afa16a868e.css (styles) 61.6 kB [initial] [rendered]
Finished Step #1
PUSH
Artifacts will be uploaded to gs://techm-test-nikunj using gsutil cp
tools/bq-visualizer/dist/*: Uploading path....
CommandException: No URLs matched: tools/bq-visualizer/dist/*
CommandException: 1 file/object could not be transferred.
ERROR
```

**Comment by boredabdel** [comment]
@nikunjbhartia There is a PR against that repo to upgraded it to Angular v12 https://github.com/GoogleCloudPlatform/professional-services/pull/715

Let's wait for it to be merged and we will see what's wrong with the tool

@smeyn Please consider making sure the tool builds.

**Comment by smeyn** [comment]
Fix is on on branch master
