### ISSUE TITLE
Creating Dataset error in examples/billboard/billboard.py

### ISSUE THREAD

**Issue by charlesg** [GoogleCloudPlatform/professional-services#930]
Regardless of how I pass the option, I can't seem to get billboard.py to like the options with `-bb BILLBOARD_DATASET`. It seems to fail trying to create the dateset with an error on name format.:

```
Creating standard Dataset.
Traceback (most recent call last):
  File "/home/cgagnon/cloudshell_open/professional-services/examples/billboard/billboard.py", line 295, in <module>
    main(sys.argv[1:])
  File "/home/cgagnon/cloudshell_open/professional-services/examples/billboard/billboard.py", line 284, in main
    create_dataset(args)  # to create dataset
  File "/home/cgagnon/cloudshell_open/professional-services/examples/billboard/billboard.py", line 75, in create_dataset
    standard_table_info = bq_client.get_table(standard_source_id)
  File "/home/cgagnon/cloudshell_open/professional-services/examples/billboard/bill-env/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 1008, in get_table
    table_ref = _table_arg_to_table_ref(table, default_project=self.project)
  File "/home/cgagnon/cloudshell_open/professional-services/examples/billboard/bill-env/lib/python3.9/site-packages/google/cloud/bigquery/table.py", line 2733, in _table_arg_to_table_ref
    value = TableReference.from_string(value, default_project=default_project)
  File "/home/cgagnon/cloudshell_open/professional-services/examples/billboard/bill-env/lib/python3.9/site-packages/google/cloud/bigquery/table.py", line 242, in from_string
    ) = _helpers._parse_3_part_id(
  File "/home/cgagnon/cloudshell_open/professional-services/examples/billboard/bill-env/lib/python3.9/site-packages/google/cloud/bigquery/_helpers.py", line 829, in _parse_3_part_id
    raise ValueError(
ValueError: table_id must be a fully-qualified ID in standard SQL format, e.g., "project.dataset.table_id", got ...
```

After got, it has a string that concatenates the names of the STANDARD_BILLING_EXPORT_DATASET and the DETAILED_BILLING_EXPORT_DATASET.

**Comment by charlesg** [comment]
Operator error, I was providing the name of the table instead of just the dataset where the table is found.
